[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/tensorflow/blob/main/Part%202/2.6_indexing.ipynb)

In [1]:
# 텐서플로 불러오기
import tensorflow as tf

# 벡터 정의하기
vec = tf.constant([10, 20, 30, 40, 50])
print(vec)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [2]:
print(vec[0])

tf.Tensor(10, shape=(), dtype=int32)


In [3]:
print(vec[-1])

tf.Tensor(50, shape=(), dtype=int32)


In [4]:
print(vec[:3])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [5]:
# 행렬 정의
mat = tf.constant([[10, 20, 30],
                  [40, 50, 60]])

print(mat[0, 2])

tf.Tensor(30, shape=(), dtype=int32)


In [6]:
print(mat[0, :])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [7]:
print(mat[:, 1])

tf.Tensor([20 50], shape=(2,), dtype=int32)


In [8]:
print(mat[:, :])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [9]:
# 랭크-3 텐서 정의
tensor = tf.constant([
    [[10, 20, 30], 
     [40, 50, 60]],
    [[-10, -20, -30], 
     [-40, -50, -60]],       
])

print(tensor)

tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)


In [10]:
print(tensor[0, :, :])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [11]:
print(tensor[:, :2, :2])

tf.Tensor(
[[[ 10  20]
  [ 40  50]]

 [[-10 -20]
  [-40 -50]]], shape=(2, 2, 2), dtype=int32)
