[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/tensorflow/blob/main/Part%202/2.7_reshape.ipynb)

In [1]:
# 텐서플로 불러오기
import tensorflow as tf

# 텐서 정의하기
tensor1 = tf.constant([[0, 1, 2], 
                      [3, 4, 5]])
print(tensor1)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [2]:
tensor_var1 = tf.Variable(tensor1)
print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>


In [3]:
print("이름: ", tensor_var1.name)
print("크기: ", tensor_var1.shape)
print("자료형: ", tensor_var1.dtype)
print("배열: ", tensor_var1.numpy())

이름:  Variable:0
크기:  (2, 3)
자료형:  <dtype: 'int32'>
배열:  [[0 1 2]
 [3 4 5]]


In [6]:
tensor_var1.assign([[1, 1, 1],
                   [2, 2, 2]])

print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]], dtype=int32)>


In [4]:
tensor2 = tf.convert_to_tensor(tensor_var1)
print(tensor2)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [5]:
tensor_var2 = tf.Variable(tensor2, name="New Name")
print(tensor_var2.name)

New Name:0


In [6]:
tensor_var1 + tensor_var2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 0,  2,  4],
       [ 6,  8, 10]])>